---
# tasks file for plex
- name: Download Plex Media Server Package
  get_url:
    url: "{{ plex_package_url }}"
    dest: "/tmp/plexmediaserver.deb"
    validate_certs: no
  become: yes
  register: download_plex

- name: Install Plex Media Server
  apt:
    deb: "/tmp/plexmediaserver.deb"
  become: yes
  when: download_plex.changed
  notify:
   - Restart Plex Server

- name: Ensure Plex Install Directory Exists
  file:
    path: "{{ plex_install_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Copy Plex Conf. File
  template:
    src: plex_config.j2
    dest: "{{ plex_install_dir }}/config.cfg"
  become: yes

- name: Start Plex Server
  systemd:
    name: plexmediaserver
    state: started
    enabled: yes
  become: yes